apiVersion: v1 # check version using "kubectl api-resources"
kind: Pod
metadata:
  name: nginx
spec:
  containers: #There must be at least one container in a Pod.
  - name: nginx
    image: nginx:1.20
    ports:
    - containerPort: 80
    
# kubectl create -f pod.yaml 